model:
  name: yolov11n
  version: v1
  format: onnx 
  confidence_threshold: 0.4
  iou_threshold: 0.5
  classes: 
    - id: 0
      name: car
    - id: 1
      name: truck
    - id: 2
      name: motorcycle
storage:
  bucket: yolo11n-bucket
  path: yolo/v1/yolov11n.onnx
vertex_ai:
  region: us-central1
  endpoint_id: 3898139255884480512
