runtime: nodejs18
env: standard
entrypoint: node server.js

env_variables:
  DB_USER: "projects/vision-447321/secrets/DB_USER/versions/latest"
  DB_PASSWORD: "projects/vision-447321/secrets/DB_PASSWORD/versions/latest"
  DB_HOST: "projects/vision-447321/secrets/DB_HOST/versions/latest"
  DB_NAME: "projects/vision-447321/secrets/DB_NAME/versions/latest"
  DB_PORT: "projects/vision-447321/secrets/DB_PORT/versions/latest"
  PORT: '8080'
